
import java.awt.CardLayout;
import java.awt.Color;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.text.MaskFormatter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Mid-Semester Checkpoint
 * Point-Of-Sale Kiosk 
 * Dr. Patel, Megan Yates, Eric Chou, Fabian Pisztora
 * Basic Front-End GUI Card Layout with opening of correct panels
 * Note: Design and further layout features and components still necessary
 * 
 * February 18th, 2016
 * @author Megan
 */
public class Kiosk extends javax.swing.JFrame {

    /**
     * Creates new form Kiosk
     */
    public Kiosk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonPanel = new javax.swing.JPanel();
        PickUpButton = new javax.swing.JButton();
        DropOffButton = new javax.swing.JButton();
        QuestionsButton = new javax.swing.JButton();
        DisplayPanel = new javax.swing.JPanel();
        dropOffPanel = new javax.swing.JPanel();
        DropOffLabel = new javax.swing.JLabel();
        DropOffCheckbox = new javax.swing.JCheckBox();
        InsuranceNumberDropOff = new javax.swing.JTextField();
        Back_DropOff = new javax.swing.JButton();
        Submit_DropOff = new javax.swing.JButton();
        DateDropOff = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        feedbackPanel2 = new javax.swing.JPanel();
        DropOffFeedBack_ThankYou = new javax.swing.JLabel();
        DropOffFeedBack_QueueLabel = new javax.swing.JLabel();
        DropOffFeedBack_BackButton = new javax.swing.JButton();
        questionsPanel = new javax.swing.JPanel();
        QuestionsLabel = new javax.swing.JLabel();
        Scroll_Questions = new javax.swing.JScrollPane();
        List_Questions = new javax.swing.JList();
        Back_Questions = new javax.swing.JButton();
        Technician_Questions = new javax.swing.JButton();
        feedbackPanel1 = new javax.swing.JPanel();
        QuestionsFeedBack_ThankYou = new javax.swing.JLabel();
        QuestionsFeedBack_QueueLabel = new javax.swing.JLabel();
        QuestionsFeedBack_BackButton = new javax.swing.JButton();
        pickUpPanel = new javax.swing.JPanel();
        PickUpLabel = new javax.swing.JLabel();
        PickUpCheckbox = new javax.swing.JCheckBox();
        FirstNamePickUp = new javax.swing.JTextField();
        LastNamePickUp = new javax.swing.JTextField();
        Submit_PickUp = new javax.swing.JButton();
        Back_PickUp = new javax.swing.JButton();
        DatePickUp = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        feedbackPanel = new javax.swing.JPanel();
        PickUpFeedBack_ThankYou = new javax.swing.JLabel();
        PickUpFeedBack_QueueLabel = new javax.swing.JLabel();
        PickUpFeedBack_BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        ButtonPanel.setBackground(new java.awt.Color(153, 204, 255));

        PickUpButton.setBackground(new java.awt.Color(255, 255, 204));
        PickUpButton.setFont(new java.awt.Font("Copperplate", 1, 36)); // NOI18N
        PickUpButton.setText("Pick Up");
        PickUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PickUpButtonActionPerformed(evt);
            }
        });

        DropOffButton.setBackground(new java.awt.Color(255, 255, 204));
        DropOffButton.setFont(new java.awt.Font("Copperplate", 1, 36)); // NOI18N
        DropOffButton.setText("Drop Off");
        DropOffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropOffButtonActionPerformed(evt);
            }
        });

        QuestionsButton.setBackground(new java.awt.Color(255, 255, 204));
        QuestionsButton.setFont(new java.awt.Font("Copperplate", 1, 36)); // NOI18N
        QuestionsButton.setText("Questions");
        QuestionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuestionsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonPanelLayout = new javax.swing.GroupLayout(ButtonPanel);
        ButtonPanel.setLayout(ButtonPanelLayout);
        ButtonPanelLayout.setHorizontalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(PickUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DropOffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuestionsButton))
        );
        ButtonPanelLayout.setVerticalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DropOffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PickUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuestionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );

        getContentPane().add(ButtonPanel, "card2");

        DisplayPanel.setBackground(new java.awt.Color(255, 204, 204));
        DisplayPanel.setLayout(new java.awt.CardLayout());

        dropOffPanel.setBackground(new java.awt.Color(255, 204, 204));

        DropOffLabel.setFont(new java.awt.Font("Copperplate", 1, 36)); // NOI18N
        DropOffLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DropOffLabel.setText("Drop Off Information");

        DropOffCheckbox.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        DropOffCheckbox.setText("Returning Customer");
        DropOffCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropOffCheckboxActionPerformed(evt);
            }
        });

        InsuranceNumberDropOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsuranceNumberDropOffActionPerformed(evt);
            }
        });

        Back_DropOff.setBackground(new java.awt.Color(255, 255, 204));
        Back_DropOff.setFont(new java.awt.Font("Copperplate", 1, 24)); // NOI18N
        Back_DropOff.setText("BACK");
        Back_DropOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_DropOffActionPerformed(evt);
            }
        });

        Submit_DropOff.setBackground(new java.awt.Color(255, 255, 204));
        Submit_DropOff.setFont(new java.awt.Font("Copperplate", 1, 24)); // NOI18N
        Submit_DropOff.setText("Submit");
        Submit_DropOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_DropOffActionPerformed(evt);
            }
        });

        try {
            DateDropOff.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        DateDropOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateDropOffActionPerformed(evt);
            }
        });

        jLabel4.setText("Date of Birth:");

        jLabel5.setText("Insurance Card Number:");

        jLabel6.setText("Relationship to Patient:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Self", "Relative", "Friend", "Other" }));

        javax.swing.GroupLayout dropOffPanelLayout = new javax.swing.GroupLayout(dropOffPanel);
        dropOffPanel.setLayout(dropOffPanelLayout);
        dropOffPanelLayout.setHorizontalGroup(
            dropOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dropOffPanelLayout.createSequentialGroup()
                .addGroup(dropOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dropOffPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Back_DropOff, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dropOffPanelLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(dropOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DropOffCheckbox)
                            .addGroup(dropOffPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DateDropOff))
                            .addGroup(dropOffPanelLayout.createSequentialGroup()
                                .addGroup(dropOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(dropOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(InsuranceNumberDropOff, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                                    .addGroup(dropOffPanelLayout.createSequentialGroup()
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dropOffPanelLayout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addGroup(dropOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dropOffPanelLayout.createSequentialGroup()
                        .addComponent(DropOffLabel)
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dropOffPanelLayout.createSequentialGroup()
                        .addComponent(Submit_DropOff)
                        .addGap(271, 271, 271))))
        );
        dropOffPanelLayout.setVerticalGroup(
            dropOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dropOffPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(DropOffLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(DropOffCheckbox)
                .addGap(18, 18, 18)
                .addGroup(dropOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dropOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsuranceNumberDropOff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(13, 13, 13)
                .addGroup(dropOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateDropOff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(Submit_DropOff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(Back_DropOff, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        DisplayPanel.add(dropOffPanel, "dropOff");

        feedbackPanel2.setBackground(new java.awt.Color(255, 204, 204));

        DropOffFeedBack_ThankYou.setFont(new java.awt.Font("Savoye LET", 1, 70)); // NOI18N
        DropOffFeedBack_ThankYou.setText("Thank you!");

        DropOffFeedBack_QueueLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        DropOffFeedBack_QueueLabel.setText("Your queue number is");

        DropOffFeedBack_BackButton.setBackground(new java.awt.Color(255, 255, 204));
        DropOffFeedBack_BackButton.setFont(new java.awt.Font("Copperplate", 1, 36)); // NOI18N
        DropOffFeedBack_BackButton.setText("BACK");
        DropOffFeedBack_BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropOffFeedBack_BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout feedbackPanel2Layout = new javax.swing.GroupLayout(feedbackPanel2);
        feedbackPanel2.setLayout(feedbackPanel2Layout);
        feedbackPanel2Layout.setHorizontalGroup(
            feedbackPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, feedbackPanel2Layout.createSequentialGroup()
                .addGroup(feedbackPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(feedbackPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DropOffFeedBack_ThankYou, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, feedbackPanel2Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(feedbackPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DropOffFeedBack_BackButton)
                            .addComponent(DropOffFeedBack_QueueLabel))
                        .addGap(0, 95, Short.MAX_VALUE)))
                .addGap(169, 169, 169))
        );
        feedbackPanel2Layout.setVerticalGroup(
            feedbackPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, feedbackPanel2Layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(DropOffFeedBack_ThankYou, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DropOffFeedBack_QueueLabel)
                .addGap(33, 33, 33)
                .addComponent(DropOffFeedBack_BackButton)
                .addGap(126, 126, 126))
        );

        DisplayPanel.add(feedbackPanel2, "feedback");

        questionsPanel.setBackground(new java.awt.Color(255, 204, 204));

        QuestionsLabel.setFont(new java.awt.Font("Copperplate", 1, 36)); // NOI18N
        QuestionsLabel.setText("Frequently Asked Questions");

        List_Questions.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        Scroll_Questions.setViewportView(List_Questions);

        Back_Questions.setBackground(new java.awt.Color(255, 255, 204));
        Back_Questions.setFont(new java.awt.Font("Copperplate", 1, 24)); // NOI18N
        Back_Questions.setText("BACK");
        Back_Questions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_QuestionsActionPerformed(evt);
            }
        });

        Technician_Questions.setBackground(new java.awt.Color(255, 255, 204));
        Technician_Questions.setFont(new java.awt.Font("Copperplate", 3, 24)); // NOI18N
        Technician_Questions.setText("Talk to Technician");
        Technician_Questions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Technician_QuestionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout questionsPanelLayout = new javax.swing.GroupLayout(questionsPanel);
        questionsPanel.setLayout(questionsPanelLayout);
        questionsPanelLayout.setHorizontalGroup(
            questionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, questionsPanelLayout.createSequentialGroup()
                .addGap(0, 104, Short.MAX_VALUE)
                .addGroup(questionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Scroll_Questions, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuestionsLabel))
                .addGap(62, 62, 62))
            .addGroup(questionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back_Questions, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, questionsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Technician_Questions, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
        );
        questionsPanelLayout.setVerticalGroup(
            questionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionsPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(QuestionsLabel)
                .addGap(18, 18, 18)
                .addComponent(Scroll_Questions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Technician_Questions, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(Back_Questions, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        DisplayPanel.add(questionsPanel, "questions");

        feedbackPanel1.setBackground(new java.awt.Color(255, 204, 204));

        QuestionsFeedBack_ThankYou.setFont(new java.awt.Font("Savoye LET", 1, 70)); // NOI18N
        QuestionsFeedBack_ThankYou.setText("Thank you!");

        QuestionsFeedBack_QueueLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        QuestionsFeedBack_QueueLabel.setText("Your queue number is");

        QuestionsFeedBack_BackButton.setBackground(new java.awt.Color(255, 255, 204));
        QuestionsFeedBack_BackButton.setFont(new java.awt.Font("Copperplate", 1, 36)); // NOI18N
        QuestionsFeedBack_BackButton.setText("BACK");
        QuestionsFeedBack_BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuestionsFeedBack_BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout feedbackPanel1Layout = new javax.swing.GroupLayout(feedbackPanel1);
        feedbackPanel1.setLayout(feedbackPanel1Layout);
        feedbackPanel1Layout.setHorizontalGroup(
            feedbackPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, feedbackPanel1Layout.createSequentialGroup()
                .addGroup(feedbackPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(feedbackPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(QuestionsFeedBack_ThankYou, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, feedbackPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(feedbackPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(QuestionsFeedBack_BackButton)
                            .addComponent(QuestionsFeedBack_QueueLabel))
                        .addGap(0, 95, Short.MAX_VALUE)))
                .addGap(169, 169, 169))
        );
        feedbackPanel1Layout.setVerticalGroup(
            feedbackPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, feedbackPanel1Layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(QuestionsFeedBack_ThankYou, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(QuestionsFeedBack_QueueLabel)
                .addGap(33, 33, 33)
                .addComponent(QuestionsFeedBack_BackButton)
                .addGap(126, 126, 126))
        );

        DisplayPanel.add(feedbackPanel1, "feedback");

        pickUpPanel.setBackground(new java.awt.Color(255, 204, 204));

        PickUpLabel.setFont(new java.awt.Font("Copperplate", 1, 36)); // NOI18N
        PickUpLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PickUpLabel.setText("Pick Up Information");
        PickUpLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PickUpLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PickUpLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        PickUpCheckbox.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        PickUpCheckbox.setText("Returning Customer");
        PickUpCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PickUpCheckboxActionPerformed(evt);
            }
        });

        FirstNamePickUp.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        FirstNamePickUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNamePickUpActionPerformed(evt);
            }
        });

        LastNamePickUp.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        LastNamePickUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNamePickUpActionPerformed(evt);
            }
        });

        Submit_PickUp.setBackground(new java.awt.Color(255, 255, 204));
        Submit_PickUp.setFont(new java.awt.Font("Copperplate", 1, 24)); // NOI18N
        Submit_PickUp.setText("Submit");
        Submit_PickUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_PickUpActionPerformed(evt);
            }
        });

        Back_PickUp.setBackground(new java.awt.Color(255, 255, 204));
        Back_PickUp.setFont(new java.awt.Font("Copperplate", 1, 24)); // NOI18N
        Back_PickUp.setText("BACK");
        Back_PickUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_PickUpActionPerformed(evt);
            }
        });

        try {
            DatePickUp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        DatePickUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatePickUpActionPerformed(evt);
            }
        });

        jLabel1.setText("Date of Birth:");

        jLabel2.setText("Last Name:");

        jLabel3.setText("First Name:");

        javax.swing.GroupLayout pickUpPanelLayout = new javax.swing.GroupLayout(pickUpPanel);
        pickUpPanel.setLayout(pickUpPanelLayout);
        pickUpPanelLayout.setHorizontalGroup(
            pickUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pickUpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pickUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pickUpPanelLayout.createSequentialGroup()
                        .addComponent(Back_PickUp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(562, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pickUpPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pickUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pickUpPanelLayout.createSequentialGroup()
                                .addGroup(pickUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PickUpCheckbox)
                                    .addGroup(pickUpPanelLayout.createSequentialGroup()
                                        .addGroup(pickUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pickUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(FirstNamePickUp)
                                            .addComponent(DatePickUp)
                                            .addComponent(LastNamePickUp, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(PickUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(72, 72, 72))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pickUpPanelLayout.createSequentialGroup()
                                .addComponent(Submit_PickUp)
                                .addGap(271, 271, 271))))))
        );
        pickUpPanelLayout.setVerticalGroup(
            pickUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pickUpPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(PickUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(PickUpCheckbox)
                .addGap(18, 18, 18)
                .addGroup(pickUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNamePickUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pickUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastNamePickUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pickUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DatePickUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(Submit_PickUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(Back_PickUp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        DisplayPanel.add(pickUpPanel, "pickUp");

        feedbackPanel.setBackground(new java.awt.Color(255, 204, 204));

        PickUpFeedBack_ThankYou.setFont(new java.awt.Font("Savoye LET", 1, 70)); // NOI18N
        PickUpFeedBack_ThankYou.setText("Thank you!");

        PickUpFeedBack_QueueLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        PickUpFeedBack_QueueLabel.setText("Your queue number is");

        PickUpFeedBack_BackButton.setBackground(new java.awt.Color(255, 255, 204));
        PickUpFeedBack_BackButton.setFont(new java.awt.Font("Copperplate", 1, 36)); // NOI18N
        PickUpFeedBack_BackButton.setText("BACK");
        PickUpFeedBack_BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PickUpFeedBack_BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout feedbackPanelLayout = new javax.swing.GroupLayout(feedbackPanel);
        feedbackPanel.setLayout(feedbackPanelLayout);
        feedbackPanelLayout.setHorizontalGroup(
            feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, feedbackPanelLayout.createSequentialGroup()
                .addGroup(feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(feedbackPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PickUpFeedBack_ThankYou, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, feedbackPanelLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PickUpFeedBack_BackButton)
                            .addComponent(PickUpFeedBack_QueueLabel))
                        .addGap(0, 95, Short.MAX_VALUE)))
                .addGap(169, 169, 169))
        );
        feedbackPanelLayout.setVerticalGroup(
            feedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, feedbackPanelLayout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(PickUpFeedBack_ThankYou, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PickUpFeedBack_QueueLabel)
                .addGap(33, 33, 33)
                .addComponent(PickUpFeedBack_BackButton)
                .addGap(126, 126, 126))
        );

        DisplayPanel.add(feedbackPanel, "feedback");

        getContentPane().add(DisplayPanel, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PickUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PickUpButtonActionPerformed
        ButtonPanel.setVisible(false);
        DisplayPanel.setVisible(true);
        CardLayout card = (CardLayout)DisplayPanel.getLayout();
        card.show(DisplayPanel, "pickUp");
    }//GEN-LAST:event_PickUpButtonActionPerformed

    private void Back_QuestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_QuestionsActionPerformed
        DisplayPanel.setVisible(false);
        ButtonPanel.setVisible(true);
    }//GEN-LAST:event_Back_QuestionsActionPerformed

    private void PickUpFeedBack_BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PickUpFeedBack_BackButtonActionPerformed
        DisplayPanel.setVisible(false);
        ButtonPanel.setVisible(true);
    }//GEN-LAST:event_PickUpFeedBack_BackButtonActionPerformed

    private void Technician_QuestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Technician_QuestionsActionPerformed
        DisplayPanel.setVisible(true);
        CardLayout card = (CardLayout)DisplayPanel.getLayout();
        card.next(DisplayPanel);
        //card.show(DisplayPanel, "feedBack");
    }//GEN-LAST:event_Technician_QuestionsActionPerformed

    private void DropOffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropOffButtonActionPerformed
        ButtonPanel.setVisible(false);
        DisplayPanel.setVisible(true);
        CardLayout card = (CardLayout)DisplayPanel.getLayout();
        card.show(DisplayPanel, "dropOff");
    }//GEN-LAST:event_DropOffButtonActionPerformed

    private void QuestionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuestionsButtonActionPerformed
        ButtonPanel.setVisible(false);
        DisplayPanel.setVisible(true);
        CardLayout card = (CardLayout)DisplayPanel.getLayout();
        card.show(DisplayPanel, "questions");
    }//GEN-LAST:event_QuestionsButtonActionPerformed

    private void QuestionsFeedBack_BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuestionsFeedBack_BackButtonActionPerformed
        DisplayPanel.setVisible(false);
        ButtonPanel.setVisible(true);
    }//GEN-LAST:event_QuestionsFeedBack_BackButtonActionPerformed

    private void DropOffFeedBack_BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropOffFeedBack_BackButtonActionPerformed
        DisplayPanel.setVisible(false);
        ButtonPanel.setVisible(true);
    }//GEN-LAST:event_DropOffFeedBack_BackButtonActionPerformed

    private void DatePickUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatePickUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DatePickUpActionPerformed

    private void Back_PickUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_PickUpActionPerformed
        DisplayPanel.setVisible(false);
        ButtonPanel.setVisible(true);
    }//GEN-LAST:event_Back_PickUpActionPerformed

    private void Submit_PickUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_PickUpActionPerformed
        DisplayPanel.setVisible(true);
        CardLayout card = (CardLayout)DisplayPanel.getLayout();
        card.next(DisplayPanel);
        //card.show(DisplayPanel, "feedBack");
    }//GEN-LAST:event_Submit_PickUpActionPerformed

    private void LastNamePickUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNamePickUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNamePickUpActionPerformed

    private void FirstNamePickUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNamePickUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNamePickUpActionPerformed

    private void PickUpCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PickUpCheckboxActionPerformed
        // TODO add your handling code here:
        if (pickUpCheckboxBoolean) {
            DatePickUp.setEditable(true);
            DatePickUp.setBackground(Color.WHITE);
            
            pickUpCheckboxBoolean = false;
        }
        else {
            DatePickUp.setEditable(false);
            DatePickUp.setBackground(Color.LIGHT_GRAY);
            
            pickUpCheckboxBoolean = true;
        }
    }//GEN-LAST:event_PickUpCheckboxActionPerformed

    private void DateDropOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateDropOffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateDropOffActionPerformed

    private void Submit_DropOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_DropOffActionPerformed
        DisplayPanel.setVisible(true);
        CardLayout card = (CardLayout)DisplayPanel.getLayout();
        card.next(DisplayPanel);
        //card.show(DisplayPanel, "feedBack");
    }//GEN-LAST:event_Submit_DropOffActionPerformed

    private void Back_DropOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_DropOffActionPerformed
        DisplayPanel.setVisible(false);
        ButtonPanel.setVisible(true);
    }//GEN-LAST:event_Back_DropOffActionPerformed

    private void InsuranceNumberDropOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsuranceNumberDropOffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsuranceNumberDropOffActionPerformed

    private void DropOffCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropOffCheckboxActionPerformed
        // TODO add your handling code here:
        if (dropOffCheckboxBoolean) {
            DateDropOff.setEditable(true);
            DateDropOff.setBackground(Color.WHITE);
            InsuranceNumberDropOff.setEditable(true);
            InsuranceNumberDropOff.setBackground(Color.WHITE);
            
            dropOffCheckboxBoolean = false;
        }
        else {
            DateDropOff.setEditable(false);
            DateDropOff.setBackground(Color.LIGHT_GRAY);
            InsuranceNumberDropOff.setEditable(false);
            InsuranceNumberDropOff.setBackground(Color.LIGHT_GRAY);
            
            dropOffCheckboxBoolean = true;
        }
    }//GEN-LAST:event_DropOffCheckboxActionPerformed
    /*
    jCalendarButton1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateOnlyPopupChanged(evt);
            }
        });
*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kiosk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kiosk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kiosk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kiosk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kiosk().setVisible(true);
            }
        });
    }
	
    Boolean pickUpCheckboxBoolean = false;
    Boolean dropOffCheckboxBoolean = false;
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_DropOff;
    private javax.swing.JButton Back_PickUp;
    private javax.swing.JButton Back_Questions;
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JFormattedTextField DateDropOff;
    private javax.swing.JFormattedTextField DatePickUp;
    private javax.swing.JPanel DisplayPanel;
    private javax.swing.JButton DropOffButton;
    private javax.swing.JCheckBox DropOffCheckbox;
    private javax.swing.JButton DropOffFeedBack_BackButton;
    private javax.swing.JLabel DropOffFeedBack_QueueLabel;
    private javax.swing.JLabel DropOffFeedBack_ThankYou;
    private javax.swing.JLabel DropOffLabel;
    private javax.swing.JTextField FirstNamePickUp;
    private javax.swing.JTextField InsuranceNumberDropOff;
    private javax.swing.JTextField LastNamePickUp;
    private javax.swing.JList List_Questions;
    private javax.swing.JButton PickUpButton;
    private javax.swing.JCheckBox PickUpCheckbox;
    private javax.swing.JButton PickUpFeedBack_BackButton;
    private javax.swing.JLabel PickUpFeedBack_QueueLabel;
    private javax.swing.JLabel PickUpFeedBack_ThankYou;
    private javax.swing.JLabel PickUpLabel;
    private javax.swing.JButton QuestionsButton;
    private javax.swing.JButton QuestionsFeedBack_BackButton;
    private javax.swing.JLabel QuestionsFeedBack_QueueLabel;
    private javax.swing.JLabel QuestionsFeedBack_ThankYou;
    private javax.swing.JLabel QuestionsLabel;
    private javax.swing.JScrollPane Scroll_Questions;
    private javax.swing.JButton Submit_DropOff;
    private javax.swing.JButton Submit_PickUp;
    private javax.swing.JButton Technician_Questions;
    private javax.swing.JPanel dropOffPanel;
    private javax.swing.JPanel feedbackPanel;
    private javax.swing.JPanel feedbackPanel1;
    private javax.swing.JPanel feedbackPanel2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel pickUpPanel;
    private javax.swing.JPanel questionsPanel;
    // End of variables declaration//GEN-END:variables
}
